on:
  push:
    branches:
    - master
    - main
  schedule:
    - cron: "15 * * * *"

name: Render GitHub Page

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages("dplyr")
          install.packages("tidyr")
          install.packages("plotly")
          install.packages("rmarkdown")
        shell: Rscript {0}
      - name: Render Site
        run: Rscript -e 'rmarkdown::render("./docs/index.Rmd", output_format = "html_document")'
      - name: Commit results
        run: |
          git add -A
          git commit index.html -m 'rebuild index.html' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
