name: render-gh-pages

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install libcurl on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: |
          install.packages("dplyr")
          install.packages("tidyr")
          install.packages("httr")
          install.packages("plotly")
          install.packages("rmarkdown")
          print(getwd())
          print(dir(getwd()))
        shell: Rscript {0}
      - name: Render Site
        working-directory: ${{env.working-directory}}
        run: |
          rmarkdown::render(
            input = file.path(getwd(), "docs", "index.Rmd"),
            output_format = "html_document",
            output_file = "index.html"
          )
        shell: Rscript {0}
      - name: Commit results
        run: |
          git rev-parse --show-toplevel
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -am "scheduled update" || echo "no changes to commit"
          git push origin || echo "no changes to commit"
