name: Render GitHub Page

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install libcurl on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install dependencies
        run: |
          install.packages("dplyr")
          install.packages("tidyr")
          install.packages("httr")
          install.packages("plotly")
          install.packages("rmarkdown")
        shell: Rscript {0}
      - name: Render Site
        run: Rscript -e 'rmarkdown::render("./docs/index.Rmd", output_format = "html_document")'
      - name: Commit results
        run: |
          git add -A
          git commit ./docs/index.html -m 'rebuild index.html' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
